#!/usr/bin/env python3
"""Sync verified blind scientific state into the IBVF map manifest."""
from __future__ import annotations
import argparse, json
from datetime import datetime, timezone
from pathlib import Path

def now(): return datetime.now(timezone.utc).isoformat().replace('+00:00','Z')
def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--manifest',required=True,type=Path); ap.add_argument('--features',required=True,type=Path); ap.add_argument('--timebasis',required=True,type=Path); ap.add_argument('--sampling-contract',required=True,type=Path)
    ap.add_argument('--sentinel-r1',required=True,type=Path); ap.add_argument('--sentinel-r2-contract',required=True,type=Path); ap.add_argument('--sentinel-r2-prereq-contract',required=True,type=Path); ap.add_argument('--sentinel-r2-prereq-report',required=True,type=Path); ap.add_argument('--ellipsoidal-dem-report',required=True,type=Path)
    ap.add_argument('--parallel-a0-pool',required=True,type=Path); ap.add_argument('--meteorological-ranking-contract',required=True,type=Path)
    a=ap.parse_args()
    m=json.loads(a.manifest.read_text(encoding='utf-8')); f=json.loads(a.features.read_text(encoding='utf-8')); t=json.loads(a.timebasis.read_text(encoding='utf-8')); s=json.loads(a.sampling_contract.read_text(encoding='utf-8'))
    r=json.loads(a.sentinel_r1.read_text(encoding='utf-8')); r2=json.loads(a.sentinel_r2_contract.read_text(encoding='utf-8')); rpc=json.loads(a.sentinel_r2_prereq_contract.read_text(encoding='utf-8')); rpr=json.loads(a.sentinel_r2_prereq_report.read_text(encoding='utf-8')); edem=json.loads(a.ellipsoidal_dem_report.read_text(encoding='utf-8'))
    pool=json.loads(a.parallel_a0_pool.read_text(encoding='utf-8')); rank=json.loads(a.meteorological_ranking_contract.read_text(encoding='utf-8'))
    assert f['feature_status']=='FROZEN_BLIND_OBSERVATIONAL_FEATURES' and f['raw_identity']['match'] is True
    assert t['source_raw_identity']['match'] is True and t['event_time_used'] is False
    assert r['r1_status']=='COMPLETE_BOTH_DATES_NO_COMPARISON' and r['comparison_performed'] is False and r['terrain_correction_performed'] is False and r['common_support_established'] is False
    assert r['pre']['diagnostics']['valid_sigma0_fraction']==1.0 and r['post']['diagnostics']['valid_sigma0_fraction']==1.0
    assert rpc['status']=='PREREGISTERED_EXECUTABLE_PREREQUISITE_FREEZE_PENDING' and rpc['pre_post_difference_allowed'] is False
    assert rpr['r2_prerequisite_gate']=='PASS' and rpr['comparison_performed'] is False and rpr['pre_post_response_inspected'] is False
    assert rpr['vertical_transform_resource']['status']=='PASS' and rpr['precise_orbits']['pre']['status']=='PASS' and rpr['precise_orbits']['post']['status']=='PASS'
    assert edem['ellipsoidal_dem_gate']=='PASS' and edem['pre_post_sar_values_read'] is False and edem['comparison_performed'] is False
    assert edem['output_dem']['sha256']=='00e3305219f0400ceca1fa39708de3e2ed31708e0a37c29b96a87d88e119aab2'
    assert r2['status']=='PREREGISTERED_R2_PREREQUISITES_PASS_EXECUTION_ALLOWED_NO_DIFFERENCE_YET'
    assert r2['vertical_datum_gate']['status']=='PASS_EXPLICIT_EGM2008_TO_WGS84_ELLIPSOIDAL_DEM_FROZEN'
    assert r2['orbit_gate']['status']=='PASS_EXACT_AUX_POEORB_BOTH_DATES_FROZEN'
    assert r2['r4_difference_gate']['pre_post_difference_computed_at_contract_time'] is False
    assert pool['pool_role']=='UNASSIGNED_BLIND_WINDOW' and pool['case_control_assignment_allowed'] is False
    assert pool['summary']['unique_calendar_days_per_track']==2907 and pool['summary']['track_day_windows']==11628 and pool['summary']['track_count']==4
    assert set(pool['tracks'])=={'shingolay','pedregal','huaycoloro','san_ildefonso'} and pool['summary']['days_removed_for_sensor_missing']==0 and pool['summary']['days_removed_for_outcome']==0
    assert pool['summary']['canonical_unique_date_sequence_sha256']=='17ecb02614e5f65e96e56bc6ef1cecbf1fed755ca2dab9b563716990b8738441'
    assert rank['execution_status']=='PREREGISTERED_NOT_YET_EXECUTED' and rank['inputs_allowed']['cashahuacra_remote_magnitudes'] is False and rank['inputs_allowed']['territorial_outcomes'] is False
    objs=(m,f,t,s,r,r2,rpc,rpr,edem,pool,rank)
    assert all(x.get('production_use') is False for x in objs); assert all(x.get('production_ready') is False for x in objs); assert all(x.get('operational_alerting_enabled') is False for x in objs); assert all(x.get('uses_operational_event_none_labels') is False for x in objs)
    assert all(x.get('territorial_activation_evidence_blinded') is True for x in (m,r,r2,rpc,rpr,edem,pool,rank))
    local=t['peru_local_calendar_features']; ant=local['antecedent_ending_local_00']
    m['version']='irfen-independent-basin-validation-map-v1.9'; m['generated_at']=now(); m['blind_sampling_contract_path']='data/validation/ibvf_blind_sampling_contract.json'; m['parallel_a0_pool_path']='data/validation/ibvf_parallel_a0_pool_inventory.json'; m['parallel_a0_pool_status']='FROZEN_EXHAUSTIVE_FOUR_TRACK_CALENDAR_NO_WINDOW_SELECTED'; m['meteorological_ranking_contract_path']='data/validation/ibvf_meteorological_ranking_contract.json'; m['meteorological_ranking_status']='PREREGISTERED_NOT_EXECUTED_NO_WINDOW_SELECTED'
    m['parallel_a0_pool_summary']={'tracks':pool['tracks'],'season_count':pool['summary']['season_count'],'unique_calendar_days_per_track':pool['summary']['unique_calendar_days_per_track'],'track_day_windows':pool['summary']['track_day_windows'],'case_control_assignment_allowed':False,'meteorological_ranking_status':m['meteorological_ranking_status'],'maximum_primary_stratified_windows':rank['primary_selection']['maximum_primary_windows']}
    ac=m.setdefault('acquisition_contract',{}); ac['imerg_basin_features_script']='scripts/ibvf_imerg_basin_features_v02.py'; ac['imerg_timebasis_audit_script']='scripts/ibvf_imerg_timebasis_audit.py'; ac['blind_sampling_contract']='site/data/validation/ibvf_blind_sampling_contract.json'; ac['parallel_a0_pool']='site/data/validation/ibvf_parallel_a0_pool_inventory.json'; ac['meteorological_ranking_contract']='site/data/validation/ibvf_meteorological_ranking_contract.json'; ac['sentinel1_r1_script']='scripts/ibvf_sentinel1_r1_radiometric.py'; ac['sentinel1_r1_report']='site/data/validation/cashahuacra_sentinel1_r1.json'; ac['sentinel1_r2_contract']='site/data/validation/cashahuacra_sentinel1_r2_contract.json'; ac['sentinel1_r2_prerequisites_report']='site/data/validation/cashahuacra_sentinel1_r2_prerequisites.json'; ac['sentinel1_r2_ellipsoidal_dem_report']='site/data/validation/cashahuacra_r2_ellipsoidal_dem.json'
    lv=ac.setdefault('local_validation',{}); lv['github_actions_imerg_basin_features']='SUCCESS_432_OF_432_RAW_IDENTITY_MATCH_AREA_WEIGHTED'; lv['github_actions_imerg_timebasis_audit']='SUCCESS_UTC_AND_PERU_LOCAL_NO_EVENT_TIME_USED'; lv['blind_sampling_contract']='PREREGISTERED_BEFORE_PARALLEL_WINDOW_UNBLINDING'; lv['parallel_a0_pool']='FROZEN_2907_DAYS_PER_TRACK_4_TRACKS_11628_TRACK_DAY_WINDOWS_NO_SELECTION'; lv['meteorological_ranking_contract']='PREREGISTERED_6_FIXED_PERCENTILE_STRATA_PER_TRACK_SEASON_NO_EXECUTION'; lv['github_actions_sentinel1_a4_r1']='SUCCESS_BOTH_DATES_NATIVE_RADIOMETRIC_NO_COMPARISON'; lv['sentinel1_a4_r2_prerequisites']='PASS_VERTICAL_GRID_AND_BOTH_AUX_POEORB_SHA256_FROZEN'; lv['sentinel1_a4_r2_ellipsoidal_dem']='PASS_SHA256_00E33052_NO_SAR_RESPONSE_READ'
    c=next(x for x in m['cases'] if x.get('unit_id')=='cashahuacra'); c['framework_stage']='A4_R1_COMPLETE_R2_PREREQUISITES_PASS_EXECUTION_ALLOWED_NO_DIFFERENCE'; c['geometry_area_km2']=15.088
    c['imerg_status']=f"FROZEN_LOCAL_P3H_{local['p3h_max']['depth_mm']:.2f}_P24H_{local['p24h_total_mm']:.2f}_ANT7D_{ant['p7d_mm']:.2f}_MM"; c['imerg_basin_features_path']='data/validation/cashahuacra_imerg_basin_features.json'; c['imerg_timebasis_audit_path']='data/validation/cashahuacra_imerg_timebasis_audit.json'
    c['imerg_observational_metrics']={'time_basis':'PERU_LOCAL_CALENDAR_DAY_UTC_MINUS_5','p30m_max_mm':local['p30m_max_mm'],'p1h_max_mm':local['p1h_max']['depth_mm'],'p3h_max_mm':local['p3h_max']['depth_mm'],'p6h_max_mm':local['p6h_max']['depth_mm'],'p12h_max_mm':local['p12h_max']['depth_mm'],'p24h_mm':local['p24h_total_mm'],'antecedent_24h_mm':ant['p24h_mm'],'antecedent_72h_mm':ant['p72h_mm'],'antecedent_7d_mm':ant['p7d_mm']}; c['imerg_timebasis_sensitivity']={'utc_p24h_mm':t['utc_calendar_features']['p24h_total_mm'],'peru_local_p24h_mm':local['p24h_total_mm'],'local_minus_utc_mm':t['comparison']['p24h_local_minus_utc_mm'],'event_time_used':False}
    c['remote_sensing_status']='S1_A4_R1_COMPLETE_R2_RESOURCE_GATES_PASS_EXECUTION_ALLOWED_NO_PREPOST_DIFFERENCE_LANDSAT_QA_DIAGNOSTIC_ONLY'; c['sentinel1_r1_path']='data/validation/cashahuacra_sentinel1_r1.json'; c['sentinel1_r1_status']=r['r1_status']; c['sentinel1_r1_comparison_performed']=False; c['sentinel1_r1_common_support_established']=False; c['sentinel1_r2_contract_path']='data/validation/cashahuacra_sentinel1_r2_contract.json'; c['sentinel1_r2_prerequisites_path']='data/validation/cashahuacra_sentinel1_r2_prerequisites.json'; c['sentinel1_r2_prerequisites_status']='PASS'; c['sentinel1_r2_ellipsoidal_dem_path']='data/validation/cashahuacra_r2_ellipsoidal_dem.json'; c['sentinel1_r2_ellipsoidal_dem_sha256']=edem['output_dem']['sha256']; c['sentinel1_r2_status']=r2['status']; c['sentinel1_r2_vertical_datum_gate']=r2['vertical_datum_gate']['status']; c['sentinel1_r2_orbit_gate']=r2['orbit_gate']['status']; c['sentinel1_r2_execution_gate']=r2['r2_execution_gate']; c['sentinel1_prepost_difference_computed']=False
    for unit in pool['tracks']:
        pc=next(x for x in m['cases'] if x.get('unit_id')==unit); pc['framework_stage']='A0_EXHAUSTIVE_POOL_AND_RANKING_CONTRACT_FROZEN_NO_WINDOW_SELECTED'; pc['blind_window']='NOT_YET_SELECTED_FROM_FROZEN_POOL'; pc['a0_pool_status']='FROZEN_2907_UNASSIGNED_LOCAL_DAYS'; pc['a0_pool_path']='data/validation/ibvf_parallel_a0_pool_inventory.json'; pc['a0_case_control_role']='UNASSIGNED'; pc['meteorological_ranking_status']='PREREGISTERED_NOT_EXECUTED'; pc['blind_status']='TERRITORIAL_EVIDENCE_SEALED'
    a.manifest.write_text(json.dumps(m,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
    print(json.dumps({'version':m['version'],'cashahuacra_stage':c['framework_stage'],'r2_execution_gate':c['sentinel1_r2_execution_gate'],'track_day_windows':pool['summary']['track_day_windows'],'ranking':m['meteorological_ranking_status'],'gate':m['serious_modeling_gate']},indent=2,ensure_ascii=False)); return 0
if __name__=='__main__': raise SystemExit(main())
